### ISSUE TITLE
bug: Cache Key returns incorrect data when using same query constraints across different cache functions

### ISSUE THREAD

**Issue by andrewalc** [rgunindi/parse-cache-memory#3]
Simple example, running a count query 
```
const query = new Parse.Query("Message");
// Returns a count of 7
const numOfMessages: number = await query.countCache({sessionToken: SESSION_TOKEN });

// The unhashed cacheKey is
// {"className":"Message","query":{"where":{}},"args":[{"sessionToken":"SESSION_TOKEN"}]}
```
This will save a number to the cache for this query. Then running the same query for find...

```
const query = new Parse.Query("Message");
// findCache returns 7 instead of array!
const messages: Parse.Object[] = await query.findCache({sessionToken: SESSION_TOKEN });

// The unhashed cacheKey is equivalent to countCache
// {"className":"Message","query":{"where":{}},"args":[{"sessionToken":"SESSION_TOKEN"}]}
```

Since the [cache key](https://github.com/rgunindi/parse-cache-memory/blob/c276a617a9ea34fc2a197321c16aa8d8dbb8c0e6/index.js#L47C16-L47C16) is based only on `className` `query` and `args`, the find query is equal to the count query and this hits the cache, returning the number value from `countCache`. The expected behavior is not hit the cache and return an array of parse objects.

I think the function called needs to be accounted for in the cachekey to prevent this

**Comment by rgunindi** [comment]
Hello,

Thank you for bringing attention to the mentioned issue/bug. I will address this and provide an improved version to fix the error. Your feedback and contribution are greatly appreciated!
